"""User.confirmed

Revision ID: 06006780abfe
Revises: 5231b2c0a14a
Create Date: 2019-03-14 18:10:38.756282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06006780abfe'
down_revision = '5231b2c0a14a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
