"""empty message

Revision ID: 081fef4f3956
Revises: dbf21ca5030b
Create Date: 2019-03-27 22:17:58.333505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '081fef4f3956'
down_revision = 'dbf21ca5030b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
